# Generated by Django 5.2.11 on 2026-07-09 20:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markaz', '0007_attendance_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('expense_type', models.CharField(choices=[('salary', 'Ustozlarga maosh'), ('rent', 'Ijara'), ('utility', 'Kommunal (svet/gaz/suv)'), ('repair', "Ta'mirlash"), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Turi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Summa')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
