# Generated by Django 5.2.11 on 2026-07-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markaz', '0008_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='days',
            field=models.CharField(blank=True, default='', help_text='mon,wed,fri kabi vergul bilan ajratilgan kunlar', max_length=50, verbose_name='Dars kunlari'),
        ),
        migrations.AddField(
            model_name='group',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Tugash vaqti'),
        ),
        migrations.AddField(
            model_name='group',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Boshlanish vaqti'),
        ),
    ]
