# Generated by Django 5.2.11 on 2026-07-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markaz', '0010_alter_group_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='for_month',
            field=models.DateField(blank=True, null=True, verbose_name="Qaysi oy uchun to'lov"),
        ),
    ]
